### ISSUE TITLE
Mounting whole context into Docker container

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/adrestia-multisig-coordination#4]
This tells me the image is not portable, and should be refactored to include minimally required files at build time.
 
https://github.com/input-output-hk/adrestia-multisig-coordination/blob/799373df31d7484962572c80d092f2ab17e36ee4/docker-compose.yml#L48-L49

**Comment by AlanVerbner** [comment]
@rhyslbw the main goal for the compose is to be able to setup a dev environment locally. We can change it to make it more general.

**Comment by rhyslbw** [comment]
Please also add the build definition to the `multisig-coordination-server` service @AlanVerbner 

``` yaml
multisig-coordination-server:
    build:
      context: .
      target: mcs
    image: inputoutput/multisig-coordination-server
```
